name: Deploy homepage
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: tj-actions/changed-files@v25
        id: changed-files
        with:
          files: |
            docs
            zeus
            mkdocs.yml
            Dockerfile
      - uses: actions/setup-python@v2
        if: steps.changed-files.outputs.any_modified
        with:
          python-version: 3.x
      - run: pip install -r docs/requirements.txt
        if: steps.changed-files.outputs.any_modified
      - run: mkdocs gh-deploy --force
        if: steps.changed-files.outputs.any_modified
