name: Deploy homepage
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: tj-actions/changed-files@v25
        id: changed-files
        with:
          files: |
            docs
            zeus
            mkdocs.yml
            Dockerfile
      - uses: actions/setup-python@v2
        if: steps.changed-files.outputs.any_modified == 'true'
        with:
          python-version: 3.x
      - run: pip install -r docs/requirements.txt
        if: steps.changed-files.outputs.any_modified == 'true'
      - run: mkdocs gh-deploy --force
        if: steps.changed-files.outputs.any_modified == 'true'
      - uses: peter-evans/repository-dispatch@v2
        if: steps.changed-files.outputs.any_modified == 'true'
        with:
          token: ${{ secrets.ML_ENERGY_REPO_ACCESS_TOKEN }}
          repository: ml-energy/zeus
          event-type: pull-gh-pages
