name: Deploy homepage
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if any homepage-related files changed
        id: changed-files
        uses: tj-actions/changed-files@v25
        with:
          files: |
            docs
            zeus
            mkdocs.yml
            Dockerfile
            .github/workflows/deploy_homepage.yaml
      - name: List all homepage-related files changed
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo "$file"
          done
      - name: Setup Python
        uses: actions/setup-python@v2
        if: steps.changed-files.outputs.any_modified == 'true'
        with:
          python-version: 3.x
      - name: Install mkdocs-material-insiders
        if: steps.changed-files.outputs.any_modified == 'true'
        env:
          GH_TOKEN: ${{ secrets.MKDOCS_MATERIAL_INSIDERS_PAT }}
        run: pip install git+https://${GH_TOKEN}@github.com/jaywonchung/mkdocs-material-insiders.git
      - name: Install other homepage dependencies
        run: pip install -r docs/requirements.txt
        if: steps.changed-files.outputs.any_modified == 'true'
      - name: Build homepage
        run: mkdocs build
        if: steps.changed-files.outputs.any_modified == 'true'
      - name: Generate a small README tor ml-energy/zeus
        run: echo -e "# Zeus Homepage\nGo to https://github.com/SymbioticLab/Zeus for the main Zeus repository." > site/README.md
        if: steps.changed-files.outputs.any_modified == 'true'
      - name: Push the built homepage to ml-energy/zeus
        uses: cpina/github-action-push-to-another-repository@v1.5
        if: steps.changed-files.outputs.any_modified == 'true'
        env:
          SSH_DEPLOY_KEY: ${{ secrets.ML_ENERGY_ZEUS_SSH_KEY }}
        with:
          source-directory: site
          destination-github-username: ml-energy
          destination-repository-name: zeus
          user-name: Jae-Won Chung
          user-email: jwnchung@umich.edu
          target-branch: master
