name: Deploy homepage
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: tj-actions/changed-files@v25
        id: changed-files
        with:
          files: |
            docs
            zeus
            mkdocs.yml
            Dockerfile
            .github/workflows/deploy_homepage.yaml
      - uses: actions/setup-python@v2
        if: steps.changed-files.outputs.any_modified == 'true'
        with:
          python-version: 3.x
      - run: pip install -r docs/requirements.txt
        if: steps.changed-files.outputs.any_modified == 'true'
      - run: mkdocs build
        if: steps.changed-files.outputs.any_modified == 'true'
      - run: echo -e "# Zeus Homepage\nGo to https://github.com/SymbioticLab/Zeus for the main repository." > site/README.md
        if: steps.changed-files.outputs.any_modified == 'true'
      - uses: cpina/github-action-push-to-another-repository@main
        if: steps.changed-files.outputs.any_modified == 'true'
        env:
          SSH_DEPLOY_KEY: ${{ secrets.ML_ENERGY_ZEUS_SSH_KEY }}
        with:
          source-directory: site
          destination-github-username: ml-energy
          destination-repository-name: zeus
          user-name: Jae-Won Chung
          user-email: jwnchung@umich.edu
          target-branch: master
