name: Lint and check format

on:
  push:
    branches:
      - '**'

jobs:
  lint_and_check_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install lint tools
        run: pip install pylint black pydocstyle
      - name: Run lint
        run: |
          black --check --exclude examples/cifar100/models zeus capriccio examples
          pydocstyle --match-dir='!examples/cifar100/models' zeus capriccio examples
          pylint zeus
