name: Push Docker image

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - '.github/workflows/push_docker.yaml'
      - 'capriccio/**'
      - 'examples/**'
      - 'trace/**'
      - 'zeus/**'
      - 'zeus_monitor/**'
      - '.dockerignore'
      - 'Dockerfile'
      - 'LICENSE'
      - 'setup.py'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Generate image metadata
        if: meta
        uses: docker/metadata-action@v4
        with:
          images: symbioticlab/zeus
          tags: |
            type=ref,event=branch
            type=ref,event=tag
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=symbioticlab/zeus:buildcache
          cache-to: type=registry,ref=symbioticlab/zeus:buildcache,mode=max
