name: Push Docker image

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - '.github/workflows/push_docker.yaml'
      - 'capriccio/**'
      - 'examples/**'
      - 'trace/**'
      - 'zeus/**'
      - 'zeus_monitor/**'
      - '.dockerignore'
      - 'Dockerfile'
      - 'LICENSE'
      - 'setup.py'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and push image to ghcr.io
        uses: jaywonchung/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GHCR_PAT }}
