name: Run tests

on:
  push:
    paths:
      - '.github/workflows/test.yaml'
      - 'zeus/**'
      - 'tests/**'
      - 'setup.py'
      - 'pyproject.toml'

# Jobs initiated by previous pushes get cancelled by a new push.
concurrency:
  group: ${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: '**/setup.py'
      - name: Install Zeus and pytest
        run: pip install ".[test]"
      - name: Run tests
        run: pytest
